In [1]:
# May 7th 2019 @ DS
# This code is to import Data files and calculate properties of 
# individual tracks
#

In [227]:
import numpy as np

class TRACK(object):
    
    def __init__(self,x,y,id):
        self.x = x
        self.y = y
        self.id = id
        
    def Track_Length(self):
        self.Track_Length = len(self.x)
    
    def Calculate_SD(self):
        # Calculate square deviatios per lag for the track
        index = self.Track_Length
        sd = np.zeros([index,index])
        for lag in range(1,index):
            nsteps = (index-1)-lag+1
            sp=0
            # CHECK RANGE FOR JK ONCE MORE .
            # Keep in mind only simulated tracks are starting at 
            # (0,0)
            for jk in range(0,nsteps):
                val = np.square(self.x[sp+lag]-self.x[sp]) + np.square(self.y[sp+lag]-self.y[sp])
                sd[lag,jk] = val
                sp = sp+1  
        # STORE sqaure deviations per lag       
        self.sd = sd
        # STORE single lag displacements SLD
        self.sld = sd[1,:]
        
        
        
    def Calculate_MSD(self):
   #    Calculate mean sqaure deviations per lag for a track
        msd = np.zeros(self.Track_Length)
        for ik in range(0,self.Track_Length):
            msd[ik] = np.mean(self.sd[ik,0:self.Track_Length-ik])
        # STORE Mean Sqaure Displacemen per lag array
        self.msd =  msd  
        
        
    def Calculate_directionality(self):
        # Calculate displacement 'd' at every lag along the track
        # from its starting point
        spx = self.x[0]
        spy = self.y[0]
        maximum_lag = self.Track_Length-1
        #
        dfg = np.square(x-spx)+np.square(y-spy)
        d = np.sqrt(dfg.astype(float))
        # Figure out why ? The following line should work
        # put gives error when data is extracted using pandas
        #d = np.sqrt(np.square(x-spx)+np.square(y-spy))
        # 
        # Calculate'D' - total distance travelled upto a time 
        # point by summing up single lag displacements
        D = np.zeros(maximum_lag)
        sp=0
        for jk in range(1,maximum_lag):
            proxy = np.square(self.x[sp+1]-self.x[sp])+np.square(self.y[sp+1]-self.y[sp])
            D[jk]= np.sqrt(proxy.astype(float))
            sp=sp+1
        # Now calculate Directionality along the track
        # d@lag/D@lag
        value1 = np.zeros(maximum_lag)
        directionality = np.zeros(maximum_lag)   
        for ik in range(1,maximum_lag):
            value1[ik]= sum(D[0:ik+1])
           # directionality[ik]=np.true_divide(d[ik],value1[ik])
            directionality[ik]=float(d[ik])/float(value1[ik])

       # STORE Directionality.
        self.directionality = directionality

In [228]:
# Import CSV files
import pandas as pd
filename = '7-5-17 IL17-TdT Foxp3 Female EAE 22 DPI SC Lumb T2_a_mf Tregs.xls'
xx= pd.ExcelFile(filename)
#xx.sheetnames()
df = xx.parse('Position')
# SUb Set for x y z and id of tracks
cond_df = df.iloc[:,[0,1,2,7]]
cond_df.columns = ('X','Y','Z','ID')
cond_df = cond_df.iloc[0:4242,]
# Identify unique track ids
unique_track_ids = cond_df.ID.unique()
print 'Number of unique tracks are', len(unique_track_ids)


Number of unique tracks are 37


In [229]:
for ids in range(0,len(unique_track_ids)):
    dfg = cond_df[cond_df.ID == unique_track_ids[ids]]
    print dfg.head()
    

         X        Y        Z          ID
0  233.281  13.9669 -62367.9  1000000000
1  233.408  14.0299 -62367.8  1000000000
2  233.346  14.1164   -62368  1000000000
3  233.435  14.1297 -62368.2  1000000000
4  233.278  13.9325 -62367.8  1000000000
           X        Y        Z          ID
160  258.558  141.712 -62362.6  1000000683
161  257.901  143.157 -62362.7  1000000683
162  264.867  147.402 -62358.9  1000000683
163  265.382  148.587   -62358  1000000683
164  265.757  149.115 -62358.3  1000000683
           X        Y        Z          ID
267  258.407  123.983 -62367.4  1000001083
268  256.019  124.934 -62367.4  1000001083
269  250.027  122.107 -62368.7  1000001083
270  250.048  122.242 -62367.6  1000001083
271  251.435  123.212 -62367.8  1000001083
           X        Y        Z          ID
427  116.503   206.12   -62372  1000001416
428  116.907  205.873 -62372.3  1000001416
429  116.768  205.491 -62372.5  1000001416
430  116.976   205.34 -62372.1  1000001416
431  116.588    206.1 -

In [230]:
a = TRACK(np.array(dfg.X),np.array(dfg.Y), dfg.ID.unique())


In [231]:
a.Track_Length()

In [232]:
a.x[0:16]

array([131.98899841308594, 127.96299743652344, 128.65499877929688,
       125.66600036621094, 122.10800170898438, 121.58499908447266,
       121.38300323486328, 118.88899993896484, 117.52300262451172,
       115.86900329589844, 118.60399627685547, 120.65399932861328,
       121.33799743652344, 123.38899993896484, 124.75599670410156,
       126.12300109863281], dtype=object)

In [233]:
a.__dict__ 

{'Track_Length': 66,
 'id': array([1000013425], dtype=object),
 'x': array([131.98899841308594, 127.96299743652344, 128.65499877929688,
        125.66600036621094, 122.10800170898438, 121.58499908447266,
        121.38300323486328, 118.88899993896484, 117.52300262451172,
        115.86900329589844, 118.60399627685547, 120.65399932861328,
        121.33799743652344, 123.38899993896484, 124.75599670410156,
        126.12300109863281, 126.80699920654297, 128.1739959716797,
        126.80699920654297, 124.75599670410156, 123.38899993896484,
        122.02100372314453, 119.97100067138672, 117.91999816894531,
        117.91999816894531, 119.28700256347656, 120.65399932861328,
        121.33799743652344, 122.02100372314453, 123.38899993896484,
        122.70500183105469, 122.02100372314453, 122.70500183105469,
        122.02100372314453, 121.33799743652344, 119.28700256347656,
        116.5530014038086, 116.71099853515625, 114.58899688720703,
        113.427001953125, 112.98300170898438, 109.

In [234]:
a.Calculate_SD()

In [235]:
a.sd

array([[   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [  40.1970957 ,    0.93112293,   18.35840067, ...,    0.49706028,
           1.19274925,    0.        ],
       [  28.96868002,   11.02372183,  152.09080209, ...,    2.78839646,
           0.        ,    0.        ],
       ..., 
       [ 176.8682812 ,   64.3691183 ,   76.31395743, ...,    0.        ,
           0.        ,    0.        ],
       [ 161.67826381,   69.74934368,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [ 157.78780418,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ]])

In [236]:
a.Calculate_MSD()


In [237]:
a.msd

array([   0.        ,   14.11400613,   39.37303433,   73.54365196,
        116.28477152,  160.11853607,  212.36325836,  270.82332873,
        329.27038897,  386.53296588,  437.85488702,  478.772086  ,
        508.68267117,  538.52990097,  556.87635006,  565.92352086,
        557.3022168 ,  539.02895477,  510.4346612 ,  479.30859272,
        446.91902647,  408.37550345,  376.04816585,  353.41543431,
        331.65952367,  309.85475303,  289.44350984,  266.70703484,
        248.66743829,  239.74990918,  237.40515134,  242.54305769,
        252.51056293,  267.51186694,  286.61631714,  311.68633639,
        346.67816555,  384.46221187,  428.48690875,  474.02171773,
        518.64698351,  570.45527092,  618.04061814,  659.44122588,
        699.86674305,  715.03424911,  707.31692089,  688.74059437,
        647.79117213,  580.77038349,  502.95402701,  433.06416645,
        398.31494026,  346.52996001,  319.38012764,  236.9971252 ,
        167.02589845,  144.37688777,  127.35639977,  122.74272

In [238]:
a.Calculate_directionality()

KeyError: 1

In [138]:
spx = a.x[0]
spy = a.y[0]

In [139]:
spy

77.0824966430664

In [146]:
xx = a.x-spx
yy = a.y - spy

In [157]:
dfg = np.square(xx)+np.square(yy)

In [170]:
from math import sqrt


In [193]:
a.sd

array([[   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [  40.1970957 ,    0.93112293,   18.35840067, ...,    0.49706028,
           1.19274925,    0.        ],
       [  28.96868002,   11.02372183,  152.09080209, ...,    2.78839646,
           0.        ,    0.        ],
       ..., 
       [ 176.8682812 ,   64.3691183 ,   76.31395743, ...,    0.        ,
           0.        ,    0.        ],
       [ 161.67826381,   69.74934368,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [ 157.78780418,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ]])

In [194]:
a.sld

array([  4.01970957e+01,   9.31122929e-01,   1.83584007e+01,
         6.71429719e+01,   3.08799664e-01,   1.34496242e+00,
         7.32507570e+00,   2.00530054e+00,   3.87573235e+01,
         4.46548065e+01,   9.24657573e+00,   1.65988216e+00,
         1.21895038e+01,   5.36631808e+00,   1.80210701e+01,
         8.80205573e+00,   4.29884602e+00,   1.44676269e+01,
         2.55242215e+01,   4.76243229e+00,   1.69141610e+01,
         1.67617364e+01,   2.15230344e+01,   1.90706941e+01,
         5.17854547e+00,   2.08194257e+00,   1.13604921e+01,
         1.16481311e+01,   2.12081891e+00,   1.24613404e+00,
         7.58598095e-01,   6.90624858e+00,   7.09588936e+00,
         6.53926344e+00,   4.42438671e+00,   7.76463555e+00,
         7.57188059e-01,   6.83645072e+00,   4.95339922e+00,
         7.79765930e-01,   1.03489194e+01,   6.48535657e-01,
         7.87470683e-01,   6.45337059e+01,   2.76588749e+01,
         6.90007920e-01,   3.80887766e-03,   1.23073419e-01,
         2.74639313e-02,

In [239]:
spx = a.x[0]
spy = a.y[0]
maximum_lag = a.Track_Length-1
        #
dfg = np.square(a.x-spx)+np.square(a.y-spy)
d = np.sqrt(dfg.astype(float))

In [252]:
D = np.zeros(maximum_lag)
sp=0
for jk in range(1,maximum_lag):
    proxy = np.square(a.x[sp+1]-a.x[sp])+np.square(a.y[sp+1]-a.y[sp])
    D[jk]= np.sqrt(proxy)
    sp=sp+1
    # Now calculate Directionality along the track
    # d@lag/D@lag
    value1 = np.zeros(maximum_lag)
    directionality = np.zeros(maximum_lag)   
    for ik in range(1,maximum_lag):
        value1[ik]= sum(D[0:ik+1])
        directionality[ik]=np.true_divide(d[ik],value1[ik])
       



In [255]:
len(d)

66