In [187]:
import numpy as np

class TRACK(object):
    
    def __init__(self,x,y,id):
        self.x = x
        self.y = y
        self.id = id
        
    def Track_Length(self):
        self.Track_Length = len(self.x)
    
    def Calculate_SD(self):
        # Calculate square deviatios per lag for the track
        index = self.Track_Length
        sd = np.zeros([index,index])
        for lag in range(1,index):
            nsteps = (index-1)-lag+1
            sp=0
            # CHECK RANGE FOR JK ONCE MORE .
            # Keep in mind only simulated tracks are starting at 
            # (0,0)
            for jk in range(0,nsteps):
                val = np.square(self.x[sp+lag]-self.x[sp]) + np.square(self.y[sp+lag]-self.y[sp])
                sd[lag,jk] = val
                sp = sp+1  
        # STORE sqaure deviations per lag       
        self.sd = sd
        # STORE single lag displacements SLD
        self.sld = sd[1,:]
        
        
        
    def Calculate_MSD(self):
   #    Calculate mean sqaure deviations per lag for a track
        msd = np.zeros(self.Track_Length)
        for ik in range(0,self.Track_Length):
            msd[ik] = np.mean(self.sd[ik,0:self.Track_Length-ik])
        # STORE Mean Sqaure Displacemen per lag array
        self.msd =  msd  
        
        
    def Calculate_directionality(self):
        # Calculate displacement 'd' at every lag along the track
        # from its starting point
        spx = self.x[0]
        spy = self.y[0]
        maximum_lag = self.Track_Length-1
        #
        d = np.sqrt(np.square(x-spx)+np.square(y-spy))
        # Calculate'D' - total distance travelled upto a time 
        # point by summing up single lag displacements
        D = np.zeros(maximum_lag)
        sp=0
        for jk in range(1,maximum_lag):
            proxy = np.square(self.x[sp+1]-self.x[sp])+np.square(self.y[sp+1]-self.y[sp])
            D[jk]= np.sqrt(proxy)
            sp=sp+1
        # Now calculate Directionality along the track
        # d@lag/D@lag
        value1 = np.zeros(maximum_lag)
        directionality = np.zeros(maximum_lag)   
        for ik in range(1,maximum_lag):
            value1[ik]= sum(D[0:ik+1])
            directionality[ik]=np.true_divide(d[ik],value1[ik])
       # STORE Directionality.
        self.directionality = directionality
               

In [170]:
x = np.random.randint(0,10,10)
y = np.random.randint(5,15,10)
x


array([7, 1, 6, 1, 0, 9, 3, 8, 9, 8])

In [172]:
y


array([10, 11,  8,  9, 14,  5, 14, 13, 13, 13])

In [173]:
a = TRACK(x,y,'1')

In [123]:
a?


Type:        TRACK
String form: <__main__.TRACK object at 0x10cc56090>
Docstring:   <no docstring>


In [174]:
a.Track_Length()

In [175]:
a.Calculate_SD()

In [176]:
a.sd.shape

(10, 10)

In [177]:
a.sd

array([[   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [  37.,   34.,   26.,   26.,  162.,  117.,   26.,    1.,    1.,
           0.],
       [   5.,    4.,   72.,   80.,    9.,   65.,   37.,    0.,    0.,
           0.],
       [  37.,   10.,   18.,   29.,   65.,   64.,   26.,    0.,    0.,
           0.],
       [  65.,  100.,   45.,   65.,   82.,   65.,    0.,    0.,    0.,
           0.],
       [  29.,   13.,   29.,   80.,   65.,    0.,    0.,    0.,    0.,
           0.],
       [  32.,   53.,   34.,   65.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [  10.,   68.,   29.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [  13.,   53.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.],
       [  10.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.]])

In [178]:
a.Calculate_MSD()

In [179]:
a.msd

array([  0.        ,  47.77777778,  34.        ,  35.57142857,
        70.33333333,  43.2       ,  46.        ,  35.66666667,
        33.        ,  10.        ])

In [180]:
np.square(a.msd-2)

array([  4.00000000e+00,   2.09560494e+03,   1.02400000e+03,
         1.12704082e+03,   4.66944444e+03,   1.69744000e+03,
         1.93600000e+03,   1.13344444e+03,   9.61000000e+02,
         6.40000000e+01])

In [181]:
a.Calculate_directionality()

In [184]:
a.__dict__


{'Track_Length': 10,
 'directionality': array([ 0.        ,  1.        ,  0.18768857,  0.35754174,  0.36461413,
         0.15456989,  0.12390077,  0.06230432,  0.06966529]),
 'id': '1',
 'msd': array([  0.        ,  47.77777778,  34.        ,  35.57142857,
         70.33333333,  43.2       ,  46.        ,  35.66666667,
         33.        ,  10.        ]),
 'sd': array([[   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.],
        [  37.,   34.,   26.,   26.,  162.,  117.,   26.,    1.,    1.,
            0.],
        [   5.,    4.,   72.,   80.,    9.,   65.,   37.,    0.,    0.,
            0.],
        [  37.,   10.,   18.,   29.,   65.,   64.,   26.,    0.,    0.,
            0.],
        [  65.,  100.,   45.,   65.,   82.,   65.,    0.,    0.,    0.,
            0.],
        [  29.,   13.,   29.,   80.,   65.,    0.,    0.,    0.,    0.,
            0.],
        [  32.,   53.,   34.,   65.,    0.,    0.,    0.,    0.,    0.,
            0.],
        [  1

In [186]:
vars(a)

{'Track_Length': 10,
 'directionality': array([ 0.        ,  1.        ,  0.18768857,  0.35754174,  0.36461413,
         0.15456989,  0.12390077,  0.06230432,  0.06966529]),
 'id': '1',
 'msd': array([  0.        ,  47.77777778,  34.        ,  35.57142857,
         70.33333333,  43.2       ,  46.        ,  35.66666667,
         33.        ,  10.        ]),
 'sd': array([[   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
            0.],
        [  37.,   34.,   26.,   26.,  162.,  117.,   26.,    1.,    1.,
            0.],
        [   5.,    4.,   72.,   80.,    9.,   65.,   37.,    0.,    0.,
            0.],
        [  37.,   10.,   18.,   29.,   65.,   64.,   26.,    0.,    0.,
            0.],
        [  65.,  100.,   45.,   65.,   82.,   65.,    0.,    0.,    0.,
            0.],
        [  29.,   13.,   29.,   80.,   65.,    0.,    0.,    0.,    0.,
            0.],
        [  32.,   53.,   34.,   65.,    0.,    0.,    0.,    0.,    0.,
            0.],
        [  1